### ISSUE TITLE
MVP Requirements (pre-launch)

### ISSUE THREAD

**Issue by ItsJohnTheDeveloper** [ItsJohnTheDeveloper/artshow.me#4]
CRUD

### Create
- [x] Collection
- [x] Profile
- [ ] Painting
- [x] Images (S3 Bucket)
### Read
- [x] Collection
- [x] Collections
- [x] Painting
- [x] Artist
- [ ] Artists
### Update
- [ ] Collection name
- [ ] Collection Painting order
- [ ] Painting (info, images)
- [ ] Profile (info)
### Delete
- [ ] Collection (all paintings)
- [ ] Painting images

---

### TODO:
- [x] Plan & Design "Show all" (independent paintings bound to no collection) 
- [ ] UX Audit
- [ ] Design Navbar - #1 
- [ ] Design Homepage - #2 
- [ ] Design find Artists page
- [ ] Plan & Purchase domain name
- [ ] Implement homepage
- [ ] Implement find Artists page
- [ ] Staging & Prod envs
- [ ] Setup Vercel deployment (Continuous Delievery)

**Comment by ItsJohnTheDeveloper** [comment]
"Show all" implementation checklist: 
- [x] add the ability to create independent paintings without needing to add them through a collection
- [x] add the ability to view independent paintings
- [x] plan how to view all independent paintings (collections page) ie. `site.com/artist/{artist-id}/collection/show-all?artId={art-id}`. `Show all` will be a reserved collection so user's can't create a collection called `Show all`
- [x] add the ability to re-assign paintings to different collection
- [x] add a `Create collection` button in the upload painting flow
Update (Sept 5th): `Show all` will display every piece that the user has, can use pagination but don't display any collection titles - keep that for the "Collections" pills.

**Comment by ItsJohnTheDeveloper** [comment]
Closing as barebone app is complete after server refactor
